databasecoders/cloudchatroom

config.js
schema.sql

mysql database set up with user info

Database setup

---

models/orm.js
models/users.js
routes/api-routes.js

delete user function working and updating db properly
user has to enter their password in order to delete their profile

Orm delete user

---

.gitignore
firebase.js
package-lock.json

NPM Firebase-admin is required for firebase.js to operate.
A special key stored as a json is required to run, i'll attempt to add it to env doc once I get deeper into the documentation.

Basic Firebase connection

---

models/users.js
public/js/signUpForm.js
server.js

Folder redesign

---

package-lock.json
package.json
public/html/signUpForm.html
public/js/signUpForm.js
server.js

user has to enter username or error message will appear
user has to enter valid email with "@" or "." or error message will appear
user two passwords have to match or error message will appear
user has to check to agree to our terms and conditions or error message will appear
if all is complete, redirect to profile page, user data logs in mysql

Login verification

---

FirebaseStuff/Chat_text.html
FirebaseStuff/firebase-controller.js
FirebaseStuff/firebase-listenForChat.js
FirebaseStuff/firebase-logger.js

Working on setting up API endpoints for sending / receiving the text.

Firebase back-end: Send / Receive

---

public/html/main.html
public/html/newProfileForm.html
public/html/profile.html
public/html/signUpForm.html

Profile pic upload

---

controllers/userController.js
models/users.js
package-lock.json
package.json
public/styles/profile.css
public/styles/shared.css
public/styles/signUpForm.css
server.js
views/layouts/main.handlebars
views/profile.handlebars

profile page accessing referenced users info

profile page updates

---

models/orm.js
models/user-login.js
models/users.js
public/html/signIn.html
routes/api-routes.js
schema.sql

when a user signs in, it will assign a session to them in the db
if username does not exist / name+password doesn't match up, will say invalid in bash console
db has been updated with additional columns
only thing that needs work is knowing when a user is logged in and when to assign that user's session to null when they click sign out which i'll work on tomorrow
please read this and look at code in detail before approving
test out after pulling

Finish login

---

FirebaseStuff/Chat_text.html

Simple chat with auto expanding list.
Each message is added to DOM as a <p> with Jquery.

Simple Global Chat box

---

controllers/userController.js
models/users.js
public/js/chat.js
public/js/front.js
views/layouts/main.handlebars
views/profile.handlebars

cleaned up files - removed getOne call

Profile update

---

config/authorizer.js
config/config.js
models/user-login.js
models/users.js
public/html/signIn.html
public/js/signUpForm.js
routes/api-routes.js
schema.sql

need to get login, logout working

redid orm with pauls code

---

FirebaseStuff/firebase-controller.js
config/config.js
routes/api-routes.js

Uncommented FB code. All chat api routes are functional. If a Firebase issue arrives, attempt checking the .env file.

Uncommented FB code

---

models/user-login.js
models/users.js
package-lock.json
public/html/photo.html
public/html/signUpForm.html
public/js/app.js
public/js/signUpForm.js
server.js

Photo public

---

models/user-login.js
models/users.js
public/html/editprofile.html
public/html/main.html
public/html/profile.html
public/html/signIn.html
public/html/signUpForm.html
public/js/signUpForm.js
routes/api-routes.js
schema.sql

fixed navbar options
user can enter bio when signing up, info appears on main page

Html edits

---

models/users.js
public/html/editprofile.html
public/html/signUpForm.html

edit profile tab autopopulates user's info. clicks submit, updates in db

Edit profile

---

models/user-login.js
public/html/main.html
public/html/photo.html
public/html/signUpForm.html
public/js/app.js
public/js/signUpForm.js
schema.sql

allow second image upload to fb & db & display user image on main.html

Multi photo

---

controllers/userController.js
models/users.js
public/html/main.html
public/html/signUpForm.html
public/js/app.js
views/profile.handlebars

three images rendered from local storage on the main page and pushed to firebase

Three image main

---

controllers/userController.js
models/user-login.js
models/users.js
public/html/signUpForm.html
public/js/signUpForm.js
views/profile.handlebars

pulled out references to the second image in the profile creation

references removed to image_one for prof

---

public/html/globalchat.html
public/html/main.html
routes/htmlRoutes.js

New page for global chat
Tested chat with two users logged in on separate incognito windows.

Global chat backup

---

controllers/userController.js
public/html/photo.html
public/html/signUpForm.html
views/profile.handlebars

styling applied to photo upload buttons, upload progress bar and yellow bar removed from sign up page

Styling update 75
